name: language_service
description: "Simplifies multilingual support and translation management for Flutter apps."
version: 0.0.1
homepage: https://github.com/yavuzfeti/language_service

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: